# Generated by Django 3.2.4 on 2021-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20210910_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawamount',
            name='amount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
