# Generated by Django 3.2.6 on 2021-09-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_withdrawamount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('Pakage_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=50)),
                ('package_price', models.CharField(max_length=20)),
                ('package_timeperiod', models.CharField(max_length=50)),
                ('like', models.CharField(max_length=50)),
                ('follows', models.CharField(max_length=50)),
                ('subscribers', models.CharField(max_length=50)),
            ],
        ),
    ]
