# Generated by Django 3.2.6 on 2021-09-10 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_form',
            fields=[
                ('Package_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=250)),
                ('category', models.CharField(choices=[('Daily Promo', 'Daily Promo'), ('3 Days Promo', '3 Days  Promo'), ('Weekly Promo', 'Weekly Promo'), ('15 Days Promo', '15 Days Promo'), ('Monthly Promo', 'Monthly Promo'), ('Mega Promo', 'Mega Promo')], max_length=20)),
                ('id_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='transactions/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Process', 'In Process'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='pending', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
