# Generated by Django 3.2.6 on 2021-09-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_package_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package_form',
            old_name='category',
            new_name='p_category',
        ),
    ]
