# Generated by Django 3.2.8 on 2021-11-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20211108_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('contest_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='contest')),
                ('contest_head', models.CharField(max_length=200)),
                ('contest_marq', models.CharField(max_length=200)),
                ('contest_txt', models.CharField(max_length=200)),
                ('contest_points1', models.CharField(max_length=200)),
                ('contest_points2', models.CharField(max_length=200)),
                ('contest_points3', models.CharField(max_length=200)),
            ],
        ),
    ]
